version: "3.9"
#listo error de direccionamiento
services:
  app:
    build: ./web_app
    container_name: web_app
    restart: always

    expose:
      - "3000"
  #error de direccionamiento jeje
  proxy-server:
    build: ./proxy_server
    container_name: proxy_server
    restart: always

    ports:
      - "3001:3001" #SOLO EXPONDREMOS ESTE PUERTO

    depends_on:
      - app
