version: "3.9"
#listo error de direccionamiento
services:
  app:
    build: ./web_app
    container_name: web_app
    restart: always
    #listo #necesitamos agregar a nuestro sistema una manera de registrar usuarios ya que el usuario que teniamos registrado al empezar el proyecto en docker se reinicia la base de datos :)
    expose:
      - "3000"
  #error de direccionamiento jeje
  proxy-server:
    build: ./proxy_server
    container_name: proxy_server
    restart: always

    ports:
      - "3001:3001" #SOLO EXPONDREMOS ESTE PUERTO

    depends_on:
      - app
#hay que ordenar la indentacion es decir los espacios
#LISTO A CONSTRUIR NUESTRO PROYECTO
#listo
